FROM nginx:latest
WORKDIR /

COPY default.conf.template /etc/nginx/conf.d/

ENTRYPOINT ["/bin/bash","-c","envsubst '${SERVER_HOST}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]