FROM nginx:latest
WORKDIR /

RUN apt-get update && apt-get install -y gettext-base
RUN rm /etc/nginx/conf.d/default.conf
COPY default.conf.template /etc/nginx/conf.d/
RUN envsubst < etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf