FROM nginx:latest
WORKDIR /

RUN apt-get update
RUN rm /etc/nginx/conf.d/default.conf
COPY default.conf.template /etc/nginx/conf.d/
RUN envsubst ${SERVER_HOST} < etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf